apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zg1y1xtx1-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zg1y1xtx1-java-springboot-gitops