apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zg1y1xtx1-java-springboot
  janus-idp.io/tekton: zg1y1xtx1-java-springboot
  backstage.io/kubernetes-id: zg1y1xtx1-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zg1y1xtx1-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
